### PR TITLE
sortby feature fixed

### LINKED ISSUE #9: Sorting Issue with Posts
#### Issue Description:

Highlighting an issue I've encountered while using the sortby feature in the project. Despite utilizing the "sortby" feature, the posts within the project are not being sorted as expected.

#### Expected Behavior:

Upon employing the sortby feature, the posts should ideally be arranged in the specified order. However, the sorting mechanism does not seem to be working at the moment.

#### Actual Behavior:

Currently, upon selecting the sortby criteria, the page does not reflect the desired changes.

#### Steps to Reproduce:
```
Navigate to the explore page.
Select any cirteria under the sortby options.
Observe that the posts are not sorted.
```

### PR DESCRIPTION
**Pull request by SuryanshBVerma**
## Changes are made in 3 files :  

**create-post-btn.jsx :** Small fix to have the sortby dropdown option, change dynamically upon selecting any of the sort type. (UI changes)

**posts.jsx :** Handling the "posts" prop coming in from the explore-page.jsx (this prop contains the sorted posts in the order selected by the user) by conditional rendering. 

**explore-page.jsx :** Changed the default value of sortType state to "" to allow no filter on the initial load of the explore page.  Also, removed the default option in handleSort function, so that the infinite scroll works if no filter is applied.

### CODE REVIEW

**Comment by Devansh-365** [comment]
HI @SuryanshBVerma , the infinite scroll is not woking now. Can you check this bug? Also, thanks for contributing.

**Comment by SuryanshBVerma** [comment]
Do you mean the infinite scroll after you have sorted the posts?

I have made it so that when the user sorts it in a preferred way, the infinite scroll won't work, as there cannot be sorted posts showing up infinitely.

If you want it in a way that the posts should get sorted and should have infinite scroll as well, then I have to figure out another workaround to this.

**Comment by Devansh-365** [comment]
Yes, I mean infinite scroll after we have sorted the posts.

**Comment by SuryanshBVerma** [comment]
In my code, infinite scroll was earlier working only when the user had not selected any sorting category. Now, I have made the required changes so that it is on infinite scroll even when a particular sort category is selected.

**Comment by Devansh-365** [comment]
Thanks @SuryanshBVerma for contributing! Great work.

**Comment by SuryanshBVerma** [comment]
Thanks for acknowledging my work and accepting my contribution.

**Pull request merged**
